export const TYPES = {
  ACTIONS: {
    // Configuration API
    CONFIGURATION_API_SUCCESS: "CONFIGURATION_API_SUCCESS",
    CONFIGURATION_API_FAIL: "CONFIGURATION_API_FAIL",

    // Movie API
    MOVIE_POPULAR_API_SUCCESS: "MOVIE_POPULAR_API_SUCCESS",
    MOVIE_POPULAR_API_FAIL: "MOVIE_POPULAR_API_FAIL",
    MOVIE_DETAIL_API_SUCCESS: "MOVIE_DETAIL_API_SUCCESS",
    MOVIE_DETAIL_API_FAIL: "MOVIE_DETAIL_API_FAIL",

    // Collection API
    COLLECTION_API_SUCCESS: "COLLECTION_API_SUCCESS",
    COLLECTION_API_FAIL: "COLLECTION_API_FAIL",

    // Search API
    SEARCH_MOVIE_API_SUCCESS: "SEARCH_MOVIE_API_SUCCESS",
    SEARCH_MOVIE_API_FAIL: "SEARCH_MOVIE_API_FAIL",
    SEARCH_TV_API_SUCCESS: "SEARCH_TV_API_SUCCESS",
    SEARCH_TV_API_FAIL: "SEARCH_TV_API_FAIL",
    SEARCH_COLLECTION_API_SUCCESS: "SEARCH_COLLECTION_API_SUCCESS",
    SEARCH_COLLECTION_API_FAIL: "SEARCH_COLLECTION_API_FAIL",
    SEARCH_MULTI_API_SUCCESS: "SEARCH_MULTI_API_SUCCESS",
    SEARCH_MULTI_API_FAIL: "SEARCH_MULTI_API_FAIL",
  },
};
